export type Config = {
   AZURE_SEARCH_ENDPOINT: string;
   AZURE_SEARCH_INDEX: string;
   AZURE_SEARCH_API_KEY: string;

   AZURE_OPENAI_ENDPOINT: string;
   AZURE_OPENAI_API_KEY: string;
   AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT: string;
   AZURE_OPENAI_API_VERSION: string;

   MAX_CHARS: number;
   OVERLAP: number;
};

export const config: Config = {
   AZURE_SEARCH_ENDPOINT: "",
   AZURE_SEARCH_INDEX: "",
   AZURE_SEARCH_API_KEY: "",
   AZURE_OPENAI_ENDPOINT: "",
   AZURE_OPENAI_API_KEY: "",
   AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT: "",
   AZURE_OPENAI_API_VERSION: "2024-06-01",
   MAX_CHARS: 1200,
   OVERLAP: 200
};