

export type Config = {
   AZURE_SEARCH_ENDPOINT: string;
   AZURE_SEARCH_INDEX: string;
   AZURE_SEARCH_API_KEY: string;

   AZURE_OPENAI_ENDPOINT: string;
   AZURE_OPENAI_API_KEY: string;
   AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT: string;
   AZURE_OPENAI_API_VERSION: string;
};

export const config: Config = {
   AZURE_SEARCH_ENDPOINT: process.env.AZURE_SEARCH_ENDPOINT!,
   AZURE_SEARCH_INDEX: process.env.AZURE_SEARCH_INDEX!,
   AZURE_SEARCH_API_KEY: process.env.AZURE_SEARCH_API_KEY!,
   AZURE_OPENAI_ENDPOINT: process.env.AZURE_OPENAI_ENDPOINT!,
   AZURE_OPENAI_API_KEY: process.env.AZURE_OPENAI_API_KEY!,
   AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT: process.env.AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT!,
   AZURE_OPENAI_API_VERSION: process.env.AZURE_OPENAI_API_VERSION!,
};